In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Student-Performance.csv')
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [3]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [8]:
df.isnull().sum() #checking for null values

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [9]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [11]:
df['Extracurricular Activities'].value_counts()

Extracurricular Activities
No     5052
Yes    4948
Name: count, dtype: int64

In [12]:
df1 = df

In [14]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [15]:
le = LabelEncoder()
le.fit_transform(df['Extracurricular Activities'])

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [16]:
df['Extracurricular Activities'] = le.fit_transform(df['Extracurricular Activities'])

In [17]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [21]:
x = df[['Hours Studied', 'Previous Scores', 'Extracurricular Activities', 'Sleep Hours', 'Sample Question Papers Practiced']]
x

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [ ]:
y = df['Performance Index']
y

      Performance Index
0                  91.0
1                  65.0
2                  45.0
3                  36.0
4                  66.0
...                 ...
9995               23.0
9996               58.0
9997               74.0
9998               95.0
9999               64.0

[10000 rows x 1 columns]

In [23]:
from sklearn.model_selection import train_test_split

In [28]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.1)

In [29]:
xtrain

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
2300,9,64,1,9,8
8559,6,83,0,4,4
8535,6,64,1,6,9
8204,2,55,1,8,8
2001,5,78,1,7,4
...,...,...,...,...,...
797,1,67,1,7,1
8014,6,42,1,9,5
8683,5,57,1,4,5
6269,7,49,1,4,5
3143,5,69,0,9,7

In [30]:
ytest

      Performance Index
3259               32.0
3267               79.0
3277               29.0
5431               67.0
5013               66.0
...                 ...
6666               78.0
6173               85.0
9987               69.0
6028               33.0
6225               23.0

[1000 rows x 1 columns]

In [39]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.fit_transform(xtest)

In [50]:
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [43]:
lr = LinearRegression()

In [44]:
lr.fit(xtrain, ytrain)

LinearRegression()

In [54]:
ypred = lr.predict(xtest)
ypred

array([[28.88059756],
       [76.69063897],
       [27.00510146],
       [69.48107693],
       [67.75002969],
       [48.62184955],
       [33.56469185],
       [46.56075027],
       [43.56097357],
       [49.74172172],
       [25.9100853 ],
       [69.03980701],
       [37.50714132],
       [52.58024699],
       [77.93400817],
       [35.45593912],
       [71.24382331],
       [85.15081682],
       [91.15884122],
       [51.52486305],
       [36.47205579],
       [49.89081436],
       [29.08171656],
       [44.29020965],
       [42.43469042],
       [39.56081178],
       [88.35060797],
       [53.33019956],
       [31.34613469],
       [67.57138463],
       [92.97435357],
       [42.70182948],
       [54.22115777],
       [41.50195328],
       [60.0066792 ],
       [42.91053121],
       [79.94391673],
       [61.72905375],
       [61.81541563],
       [64.37531493],
       [72.56141456],
       [64.00149115],
       [60.74061169],
       [66.72121581],
       [69.94934958],
       [92.45051532],
       [73.44657182],
       [36.95533999],
       [34.44050892],
       [40.54521035],
       [72.89017011],
       [68.29458441],
       [95.74839061],
       [59.64889942],
       [65.2800315 ],
       [26.08634829],
       [66.03955961],
       [65.11146624],
       [33.87146313],
       [52.77532969],
       [36.81706676],
       [83.23379172],
       [20.32745007],
       [60.47444759],
       [36.80772656],
       [27.49571846],
       [52.67925295],
       [42.19039997],
       [69.87147767],
       [40.11163816],
       [44.90194161],
       [53.24889903],
       [77.64902436],
       [40.94652652],
       [36.30726512],
       [87.31330413],
       [73.84465132],
       [36.71592867],
       [84.65439887],
       [67.50987876],
       [72.70902798],
       [14.5959195 ],
       [26.40259908],
       [37.22173945],
       [41.53688908],
       [43.26190002],
       [91.33064315],
       [31.47543267],
       [72.11396901],
       [62.45902944],
       [62.85900572],
       [72.43955999],
       [75.65900649],
       [27.0509093 ],
       [57.04960325],
       [90.87288246],
       [62.04994832],
       [67.33666972],
       [59.97449039],
       [33.58136484],
       [51.22138107],
       [73.34041528],
       [55.78040309],
       [88.69561894],
       [61.28070535],
       [83.83819089],
       [46.39424504],
       [36.19715178],
       [46.71606143],
       [33.12103986],
       [67.51103594],
       [42.08191451],
       [38.12162029],
       [80.76922955],
       [62.73021199],
       [45.59642461],
       [20.5180717 ],
       [41.46976448],
       [75.38112013],
       [78.021345  ],
       [55.90603224],
       [83.83428671],
       [35.6275057 ],
       [93.91985952],
       [88.41021707],
       [38.70000627],
       [44.42024724],
       [46.39711677],
       [22.66601815],
       [35.28524173],
       [70.6854142 ],
       [54.02547479],
       [43.46581865],
       [44.86695317],
       [39.33756919],
       [42.7676142 ],
       [27.70691726],
       [48.96198139],
       [53.14635384],
       [48.7910151 ],
       [37.74589973],
       [38.93495653],
       [40.12617902],
       [67.38504184],
       [71.43988096],
       [66.71108338],
       [74.73537418],
       [34.87634283],
       [53.75618902],
       [75.14329813],
       [67.1145989 ],
       [82.80505526],
       [69.13881297],
       [32.74151116],
       [75.85482879],
       [38.46695279],
       [26.16788417],
       [26.7513315 ],
       [45.8107977 ],
       [60.03056025],
       [68.24644764],
       [21.28303582],
       [18.75733272],
       [76.78988028],
       [79.26415731],
       [79.42398267],
       [41.41131256],
       [68.38118164],
       [45.28988868],
       [75.78904407],
       [82.74042772],
       [52.53541411],
       [28.70195251],
       [42.47157564],
       [17.73279768],
       [24.67758814],
       [65.63958333],
       [71.1152118 ],
       [65.1252675 ],
       [27.9766206 ],
       [78.05163702],
       [57.77567476],
       [41.05616916],
       [75.59097903],
       [75.5993974 ],
       [29.42208375],
       [47.31655642],
       [81.34951231],
       [43.30176759],
       [59.99470262],
       [62.29869983],
       [64.46125924],
       [67.85042817],
       [52.88654757],
       [30.50581031],
       [54.84107275],
       [55.4163902 ],
       [55.67596112],
       [67.76944968],
       [47.22689065],
       [79.25951353],
       [79.45055273],
       [48.93913278],
       [80.04366229],
       [65.84539874],
       [28.65711963],
       [73.17943276],
       [70.96496199],
       [32.69198187],
       [51.0553801 ],
       [38.67778665],
       [70.61622957],
       [66.47893275],
       [75.49587725],
       [77.78473331],
       [51.02215885],
       [72.85671351],
       [80.88044744],
       [43.22037103],
       [32.9657287 ],
       [32.34037771],
       [51.46013947],
       [37.02196034],
       [18.47736686],
       [39.80584184],
       [75.02059334],
       [29.8058913 ],
       [17.89238768],
       [32.90611961],
       [35.26038572],
       [76.54912907],
       [37.80220493],
       [29.77253074],
       [16.95116057],
       [18.83111773],
       [81.2930678 ],
       [60.9190214 ],
       [51.01482606],
       [33.30512094],
       [69.06168066],
       [49.1363476 ],
       [51.55533729],
       [45.7565715 ],
       [52.55069457],
       [61.18426368],
       [82.19894154],
       [38.25709389],
       [53.86044877],
       [89.50351917],
       [31.44727278],
       [40.55175091],
       [87.67364819],
       [77.79597028],
       [74.02366131],
       [23.19603201],
       [69.30457859],
       [67.20639679],
       [66.91183744],
       [33.95063153],
       [38.24181342],
       [75.84474899],
       [65.25163625],
       [32.72557778],
       [50.10481279],
       [66.2259024 ],
       [21.9270672 ],
       [39.3008662 ],
       [45.77953073],
       [68.20417904],
       [57.23618139],
       [30.9118229 ],
       [33.10185522],
       [61.92157216],
       [78.44948117],
       [80.26383634],
       [26.02019864],
       [62.46966612],
       [38.95567301],
       [23.81166815],
       [52.19504692],
       [14.46564657],
       [22.78597593],
       [84.67497603],
       [50.64960286],
       [74.19675973],
       [67.37393446],
       [65.56055425],
       [60.4002445 ],
       [44.17117369],
       [35.06456343],
       [64.3812552 ],
       [94.61043835],
       [51.33664245],
       [17.03172149],
       [43.03982919],
       [61.69950133],
       [91.33320744],
       [61.9914964 ],
       [57.53027004],
       [89.06414603],
       [47.16110594],
       [81.34546882],
       [55.49969813],
       [25.93029753],
       [27.1574834 ],
       [60.6990827 ],
       [64.11648362],
       [63.76878364],
       [65.92075899],
       [59.72476393],
       [72.3183919 ],
       [61.55658432],
       [33.03113875],
       [48.00523846],
       [64.93115976],
       [66.47447169],
       [73.16135266],
       [41.19211346],
       [20.55672896],
       [64.6298245 ],
       [39.32181803],
       [73.4411358 ],
       [22.3714588 ],
       [81.85527046],
       [63.42548723],
       [45.45021829],
       [66.65073468],
       [76.97609348],
       [76.55846926],
       [69.35600466],
       [65.26097645],
       [45.59154548],
       [57.29439795],
       [45.19608339],
       [69.47504063],
       [81.00607659],
       [95.06343053],
       [55.6865978 ],
       [50.8643409 ],
       [68.58114346],
       [63.44629974],
       [92.23577729],
       [45.08523045],
       [26.27976956],
       [36.11548631],
       [27.2701084 ],
       [36.44548572],
       [86.84907497],
       [60.12687233],
       [70.02917089],
       [24.16639397],
       [90.46569812],
       [64.91871248],
       [33.11597851],
       [55.7295339 ],
       [38.69670238],
       [85.27895763],
       [44.43111927],
       [79.21114141],
       [51.40002613],
       [67.25196927],
       [21.35528899],
       [80.98512476],
       [59.10020516],
       [70.58593754],
       [44.74955967],
       [38.18007221],
       [45.20732036],
       [41.10221235],
       [81.28042371],
       [22.22236616],
       [64.13566826],
       [48.60541192],
       [62.41419656],
       [86.18524894],
       [75.67024346],
       [45.15217233],
       [49.56471913],
       [36.94586048],
       [64.78587526],
       [48.59486142],
       [33.54684711],
       [46.98558255],
       [65.61068383],
       [55.74077087],
       [52.41968203],
       [77.37039839],
       [62.92148654],
       [49.26044492],
       [24.34265697],
       [40.05533296],
       [37.65549436],
       [69.26420677],
       [29.60049346],
       [85.95517781],
       [49.3856565 ],
       [21.2527438 ],
       [45.31920575],
       [31.63037889],
       [28.30551547],
       [53.62499426],
       [86.49996788],
       [69.53598961],
       [49.65596014],
       [82.06633967],
       [37.69214422],
       [65.86421844],
       [91.20855324],
       [75.92944944],
       [53.22050379],
       [64.26153277],
       [81.18448629],
       [47.15176575],
       [48.16994295],
       [59.45999234],
       [46.25183228],
       [44.28202663],
       [43.35106153],
       [31.25005796],
       [63.11987312],
       [38.42211991],
       [91.0602002 ],
       [48.60707334],
       [42.41917461],
       [69.8899227 ],
       [48.70539283],
       [43.31984769],
       [60.12069671],
       [85.75521598],
       [54.26622601],
       [59.30560301],
       [64.34576251],
       [59.31683998],
       [79.08551226],
       [55.91421526],
       [55.1544518 ],
       [65.31032352],
       [55.80977329],
       [59.95897458],
       [42.1502635 ],
       [35.57980108],
       [28.42240472],
       [75.1992384 ],
       [34.62495493],
       [62.1262304 ],
       [31.05199291],
       [85.81482507],
       [79.75923537],
       [47.64085091],
       [60.7239387 ],
       [65.34451972],
       [36.87551867],
       [38.19186606],
       [56.56418691],
       [32.46790364],
       [36.99571181],
       [67.75509104],
       [57.85493919],
       [80.74437354],
       [36.82176317],
       [89.44391008],
       [68.52623078],
       [28.05662464],
       [53.27528688],
       [72.77425581],
       [50.99186683],
       [53.74629194],
       [31.78007182],
       [69.25877075],
       [61.75580654],
       [45.05707055],
       [41.47984427],
       [55.92154806],
       [64.63916469],
       [73.89528516],
       [58.03566324],
       [54.34019374],
       [80.46128651],
       [77.53542441],
       [88.22308204],
       [53.37940732],
       [32.42563504],
       [21.23179197],
       [71.66097683],
       [65.73681724],
       [68.06010485],
       [90.48377821],
       [53.1508149 ],
       [35.26038572],
       [42.38687519],
       [61.31025777],
       [29.84124467],
       [46.27014772],
       [80.84551163],
       [25.43711625],
       [38.74037809],
       [39.26667   ],
       [31.05719357],
       [79.12868371],
       [65.3464165 ],
       [58.36199383],
       [25.70078328],
       [72.44048181],
       [48.90493658],
       [56.67173597],
       [57.22043022],
       [28.54626668],
       [34.49681412],
       [62.61661205],
       [46.73083764],
       [75.09944021],
       [52.72529614],
       [58.31074997],
       [41.66154328],
       [63.94578623],
       [36.92248368],
       [65.07463366],
       [45.1915692 ],
       [65.11403052],
       [73.80892328],
       [34.88062167],
       [33.2600527 ],
       [75.34562744],
       [35.64697832],
       [36.82250277],
       [71.36591323],
       [87.30884306],
       [27.47030557],
       [81.04473385],
       [80.98512476],
       [49.18239079],
       [40.17478649],
       [42.28169361],
       [59.07999294],
       [47.37170445],
       [20.6273928 ],
       [76.52561295],
       [47.32571439],
       [49.21658699],
       [85.19375292],
       [47.35075262],
       [29.64110063],
       [22.3111101 ],
       [56.13085008],
       [64.06621472],
       [68.54644301],
       [37.84440143],
       [75.80107328],
       [24.32714115],
       [37.07529778],
       [37.82632133],
       [32.3368911 ],
       [23.48589495],
       [31.86178992],
       [76.69491782],
       [73.21478613],
       [69.82939179],
       [60.8908615 ],
       [40.50111707],
       [46.90203928],
       [69.81503315],
       [57.93665729],
       [28.34045127],
       [44.06575676],
       [49.37106251],
       [58.85931464],
       [83.20539648],
       [79.49887222],
       [77.9891562 ],
       [54.69649431],
       [81.43885654],
       [30.40252551],
       [70.86028467],
       [53.07048933],
       [40.86182607],
       [62.45536061],
       [25.70212318],
       [38.61010516],
       [84.52602271],
       [27.07479035],
       [69.7806016 ],
       [78.45979632],
       [29.62534946],
       [83.94476499],
       [50.9467986 ],
       [29.38055476],
       [72.50106586],
       [74.67460792],
       [50.23020659],
       [59.59992701],
       [23.72720305],
       [74.16646771],
       [15.17546266],
       [68.11971394],
       [49.45460579],
       [48.5657797 ],
       [62.40601354],
       [19.03711586],
       [41.72023055],
       [55.49505434],
       [76.17870521],
       [45.69483028],
       [53.57118612],
       [65.229023  ],
       [37.3601954 ],
       [50.92608212],
       [69.31191139],
       [29.11274819],
       [30.07693453],
       [71.51500586],
       [84.4508978 ],
       [27.69683746],
       [55.61891631],
       [57.42118428],
       [29.69717048],
       [36.76545796],
       [79.11000332],
       [69.6552078 ],
       [54.4613087 ],
       [56.42011272],
       [82.83106844],
       [55.78657871],
       [53.25079581],
       [22.67725512],
       [27.17500662],
       [65.29871189],
       [54.05222758],
       [67.85116777],
       [74.19932401],
       [69.03529282],
       [62.35978813],
       [79.14866059],
       [47.0167964 ],
       [28.29487879],
       [33.31520073],
       [57.76545565],
       [72.68574722],
       [80.83561455],
       [59.22016295],
       [72.94885738],
       [41.75516635],
       [31.14263363],
       [33.28704084],
       [43.66541554],
       [63.15076544],
       [28.34588729],
       [33.57592882],
       [93.79386543],
       [35.46150472],
       [63.25641772],
       [51.95605317],
       [72.66999606],
       [76.04610334],
       [41.96014612],
       [23.32746212],
       [28.5705224 ],
       [39.7419539 ],
       [75.26538805],
       [55.19431937],
       [24.35199716],
       [42.88981473],
       [64.63195663],
       [54.74560603],
       [52.65463229],
       [59.72072043],
       [85.78007199],
       [60.54529365],
       [64.35864195],
       [63.15076544],
       [30.06239368],
       [45.52069941],
       [67.19552476],
       [29.15238041],
       [42.03527103],
       [44.39562658],
       [46.0299968 ],
       [44.04494424],
       [86.73491814],
       [45.6218375 ],
       [30.95061947],
       [50.21626602],
       [47.75054668],
       [48.57158065],
       [28.38741628],
       [62.62479507],
       [58.62510398],
       [78.33960318],
       [27.67686059],
       [51.99484975],
       [41.69927872],
       [78.28041166],
       [94.97896543],
       [60.59440537],
       [21.46283805],
       [63.51598863],
       [42.28030109],
       [65.08471346],
       [42.56612053],
       [70.1699412 ],
       [70.67468148],
       [23.72200238],
       [73.42469816],
       [62.12409827],
       [39.48684405],
       [48.59040036],
       [69.3797035 ],
       [63.20103434],
       [50.68593119],
       [60.86558793],
       [52.84989771],
       [43.32602331],
       [90.13002734],
       [63.88617714],
       [39.95535204],
       [70.65940102],
       [71.14573918],
       [66.1836338 ],
       [41.73146752],
       [72.37102828],
       [72.64421823],
       [64.02040689],
       [44.69208271],
       [39.59426838],
       [74.15937027],
       [53.77634861],
       [57.68173015],
       [41.70215045],
       [48.37980185],
       [74.88916323],
       [25.06724927],
       [30.83255846],
       [76.36956219],
       [88.17824916],
       [61.88607947],
       [22.50099213],
       [59.2961235 ],
       [71.48397424],
       [26.96960878],
       [29.38733067],
       [38.07678741],
       [72.04971614],
       [65.79642633],
       [88.85056517],
       [71.42956581],
       [39.03585927],
       [32.17047256],
       [65.39148473],
       [76.73027119],
       [68.68582079],
       [55.84526598],
       [52.75181357],
       [38.44233213],
       [76.15482415],
       [71.73090107],
       [58.58887169],
       [37.44516475],
       [62.0103161 ],
       [75.28090386],
       [67.18544496],
       [47.56066465],
       [59.52619462],
       [77.73966508],
       [77.93424352],
       [50.11140598],
       [44.54513678],
       [30.72714154],
       [47.08672064],
       [37.19963044],
       [67.85935079],
       [33.99026374],
       [50.22988506],
       [64.22580473],
       [31.09138978],
       [32.41996367],
       [75.17902617],
       [81.91041849],
       [62.04102569],
       [66.1092485 ],
       [59.09146526],
       [68.9956606 ],
       [56.78649309],
       [67.18405243],
       [61.39601936],
       [75.4855621 ],
       [56.47665328],
       [83.35918553],
       [72.15085422],
       [78.69994725],
       [82.86526464],
       [64.28035247],
       [54.03671176],
       [47.87654077],
       [52.48960627],
       [61.83093144],
       [38.93495653],
       [79.00361144],
       [31.7718888 ],
       [87.29131985],
       [27.69024427],
       [56.1188735 ],
       [68.88113883],
       [52.38585077],
       [80.08408674],
       [39.58682496],
       [26.38164725],
       [53.72613234],
       [34.39641564],
       [51.69104624],
       [30.98280827],
       [37.55007743],
       [80.91947936],
       [42.99712844],
       [60.13951641],
       [55.8848982 ],
       [64.59953247],
       [35.29257452],
       [81.82051738],
       [65.56989444],
       [55.93516709],
       [39.40982236],
       [80.78590254],
       [91.43318835],
       [65.16099553],
       [39.50649939],
       [35.71666721],
       [69.55546223],
       [65.94537965],
       [94.04079227],
       [80.21082044],
       [70.79413502],
       [67.03997824],
       [78.05420131],
       [64.17163165],
       [45.80512634],
       [41.68036298],
       [50.47169741],
       [37.66069502],
       [80.98006341],
       [85.16015701],
       [56.41063322],
       [60.10011955],
       [64.49485515],
       [85.78337588],
       [72.45549337],
       [37.98720782],
       [39.60234077],
       [21.79563709],
       [75.07978486],
       [69.0994161 ],
       [71.68937208],
       [82.97868187],
       [56.24690368],
       [24.6599402 ],
       [57.57607787],
       [67.35005341],
       [42.35956552],
       [55.67205694],
       [73.72635496],
       [14.10683434],
       [52.03191768],
       [71.31968782],
       [43.30079263],
       [37.57102926],
       [84.20861475],
       [54.02193555],
       [73.11438765],
       [49.78465783],
       [48.80439879],
       [38.04589509],
       [95.60431642],
       [78.09963448],
       [29.19721329],
       [83.07047976],
       [32.4409155 ],
       [62.9360274 ],
       [39.9053185 ],
       [62.49145359],
       [70.9556218 ],
       [86.93897609],
       [68.40957688],
       [41.45596322],
       [74.07913088],
       [91.88905226],
       [69.36014419],
       [51.2202239 ],
       [66.99417041],
       [69.43387657],
       [59.42556079],
       [71.02628564],
       [60.47536941],
       [71.07489311],
       [72.8653141 ],
       [69.91515338],
       [40.75566954],
       [23.12634312],
       [26.41004249],
       [85.603809  ],
       [38.84151618],
       [57.60660525],
       [22.52212617],
       [59.59021215],
       [55.09177418],
       [39.74738992],
       [79.41984314],
       [29.04580631],
       [29.2026493 ],
       [50.62028579],
       [70.2310295 ],
       [41.49536009],

In [46]:
xtrain

array([[ 1.54860927, -0.30957734,  1.00713658,  1.46174799,  1.19197899],
       [ 0.38853796,  0.78490093, -0.99291399, -1.48704206, -0.20564481],
       [ 0.38853796, -0.30957734,  1.00713658, -0.30752604,  1.54138494],
       ...,
       [ 0.00184752, -0.71280618,  1.00713658, -1.48704206,  0.14376114],
       [ 0.7752284 , -1.17363914,  1.00713658, -1.48704206,  0.14376114],
       [ 0.00184752, -0.02155674, -0.99291399,  1.46174799,  0.84257304]],
      shape=(9000, 5))

In [56]:
mean_squared_error(ytest, ypred)

5.135486795928507

In [ ]:
r2_score(ytest, ypred)

0.9855053498170293

In [58]:
with open("Student-Performance-LR.pkl", 'wb') as file:
    pickle.dump((lr, scaler, le), file)